version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/blockchain"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/www"
    schedule:
      interval: "weekly"
