name: Build

on: [push]

jobs:
  build-contracts:

    name: Build smart contracts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Show NodeJS version
        run: npm --version

      - name: Install Truffle
        run: npm install truffle -g

      - name: Install Dependencies
        run: cd blockchain && npm ci

      - name: Run tests & Generate coverage
        run: cd blockchain && truffle run coverage

      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./blockchain/coverage/lcov.info

  build-webapp:

    name: Build web application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Show NodeJS version
        run: npm --version

      - name: Install Dependencies
        run: cd www && npm ci

      - name: Run tests
        run: cd www && npm run test