name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Show NodeJS version
        run: npm --version

      - name: Install Truffle
        run: npm install truffle -g

      - name: Install Dependencies
        run: cd blockchain && npm ci

      - name: Run tests
        run: cd blockchain && truffle test

      - name: Run Test Coverage
        run: cd blockchain && truffle run coverage

      - name: Generate .coveralls.yml file
        run: cd blockchain && echo "${{ secrets.DOT_COVERALLS_YML }}" > .coveralls.yml
      - name: Send Coverage Info to CoverAlls
        run: cd blockchain && cat coverage/lcov.info | npx coveralls